name: Update Checker

env:
  IMMORTALWRT_REPO_URL: https://github.com/immortalwrt/immortalwrt
  LEDE_REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'  # 每周日20:00自动运行

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Get ImmortalWRT Commit Hash
      id: immortalwrt
      run: |
        git clone --depth 1 $IMMORTALWRT_REPO_URL -b $REPO_BRANCH immortalwrt
        echo "immortalwrtCommitHash=$(git -C immortalwrt rev-parse HEAD)" >> $GITHUB_ENV

    - name: Get LEDE Commit Hash
      id: lede
      run: |
        git clone --depth 1 $LEDE_REPO_URL -b $REPO_BRANCH lede
        echo "ledeCommitHash=$(git -C lede rev-parse HEAD)" >> $GITHUB_ENV

    - name: Compare ImmortalWRT Commit Hash
      id: immortalwrt_cache
      uses: actions/cache@v2
      with:
        path: .immortalwrtCommitHash
        key: HEAD-${{ env.immortalwrtCommitHash }}

    - name: Compare LEDE Commit Hash
      id: lede_cache
      uses: actions/cache@v2
      with:
        path: .ledeCommitHash
        key: HEAD-${{ env.ledeCommitHash }}

    - name: Save New ImmortalWRT Commit Hash
      if: steps.immortalwrt_cache.outputs.cache-hit != 'true'
      run: |
        echo ${{ env.immortalwrtCommitHash }} | tee .immortalwrtCommitHash

    - name: Save New LEDE Commit Hash
      if: steps.lede_cache.outputs.cache-hit != 'true'
      run: |
        echo ${{ env.ledeCommitHash }} | tee .ledeCommitHash

    - name: Trigger ImmortalWRT Build
      if: steps.immortalwrt_cache.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: ImmortalWRT Source Code Update

    - name: Trigger LEDE Build
      if: steps.lede_cache.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: LEDE Source Code Update
