name: Multi-Repo Update Checker

env:
  IMMORTALWRT_REPO_URL: https://github.com/immortalwrt/immortalwrt
  IMMORTALWRT_REPO_BRANCH: master
  LEDE_REPO_URL: https://github.com/coolsnowwolf/lede
  LEDE_REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0' # 每周日晚上 8 点（UTC 时间）触发

jobs:
  check-immortalwrt:
    runs-on: ubuntu-latest
    name: Check ImmortalWrt Repository
    steps:
      - name: Get ImmortalWrt Commit Hash
        id: getImmortalWrtHash
        run: |
          git clone --depth 1 $IMMORTALWRT_REPO_URL -b $IMMORTALWRT_REPO_BRANCH immortalwrt
          cd immortalwrt
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Compare ImmortalWrt Commit Hash
        id: cacheImmortalWrtHash
        uses: actions/cache@main
        with:
          path: .immortalwrt-commitHash
          key: immortalwrt-${{ env.commitHash }}

      - name: Save New ImmortalWrt Commit Hash
        if: steps.cacheImmortalWrtHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ env.commitHash }} | tee .immortalwrt-commitHash

      - name: Trigger ImmortalWrt Build
        if: steps.cacheImmortalWrtHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: immortalwrt-source-code-update
          client-payload: '{"repo": "immortalwrt", "commit": "${{ env.commitHash }}"}'

  check-lede:
    runs-on: ubuntu-latest
    name: Check Lede Repository
    steps:
      - name: Get Lede Commit Hash
        id: getLedeHash
        run: |
          git clone --depth 1 $LEDE_REPO_URL -b $LEDE_REPO_BRANCH lede
          cd lede
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Compare Lede Commit Hash
        id: cacheLedeHash
        uses: actions/cache@main
        with:
          path: .lede-commitHash
          key: lede-${{ env.commitHash }}

      - name: Save New Lede Commit Hash
        if: steps.cacheLedeHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ env.commitHash }} | tee .lede-commitHash

      - name: Trigger Lede Build
        if: steps.cacheLedeHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: lede-source-code-update
          client-payload: '{"repo": "lede", "commit": "${{ env.commitHash }}"}'

  cleanup:
    runs-on: ubuntu-latest
    needs: [check-immortalwrt, check-lede]
    name: Cleanup Old Workflows
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 3
          keep_minimum_runs: 3
