name: Update Checker

env:
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'  # 每周日 20:00

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { name: "ImmortalWRT", url: "https://github.com/immortalwrt/immortalwrt", event: "Update-Immortalwrt" }
          - { name: "LEDE", url: "https://github.com/coolsnowwolf/lede", event: "Update-Lede" }

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 ${{ matrix.repo.url }} -b $REPO_BRANCH .
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: HEAD-${{ env.commitHash }}  # 缓存key与提交哈希挂钩

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ env.commitHash }} | tee .commitHash
          echo "New commit hash saved: ${{ env.commitHash }}"

      - name: Trigger build
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: ${{ matrix.repo.event }}
          repository: ${{ github.repository }}
          workflow: build-${{ matrix.repo.name | toLowerCase }}.yml

  delete_old_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 3
          keep_minimum_runs: 3
